export default [
  {
    id: 1,
    name: "Tanvir Mahmud Fahim",
    father: "Abdur Rashid",
    mother: "Mahmuda Begum",
    add: "Uttor Millik Bagha",
    nid: 3423432434,
    mStatus: "Single",
    religion: "Islam",
    contact: "tanvirmahmudfahim1313@gmail.com",
  },
  {
    id: 2,
    name: "Jerin Tasnim",
    father: "Nurul Islam",
    mother: "Selina Begum",
    add: "Rajbari, Madaripur",
    nid: 34345635345,
    mStatus: "Single",
    religion: "Islam",
    contact: "jerintasnim@gmail.com",
  },
  {
    id: 3,
    name: "Romana Hasan Rumki",
    father: "Abdur Rashid",
    mother: "Mahmuda Begum",
    add: "Uttor Millik Bagha",
    nid: 394348440,
    mStatus: "Married",
    religion: "Islam",
    contact: "romanahasan@gmail.com",
  },
  {
    id: 4,
    name: "Mehady Hasan",
    father: "Abdur Rashid",
    mother: "Mahmuda Begum",
    add: "Notun Para, Baju Bagha",
    nid: 4634534633,
    mStatus: "Married",
    religion: "Islam",
    contact: "mehadyhasan@gmail.com",
  },
  
];
